### ISSUE TITLE
Trying to view the main analyses page for a regular user crashes

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#1079]
## Describe the bug
If you try to view the main analyses page in some instances of IRIDA, it crashes. Below is some of the relevant stack traces:

```
26 Aug 2021 21:53:15,612 ERROR ca.corefacility.bioinformatics.irida.ria.web.errors.ExceptionHandlerController:117 - Unable to find ca.corefacility.bioinformatics.irida.model.user.User with id 56; nested exception is javax.persistence.EntityNotFoundException: Unable to find ca.corefacility.bioinformatics.irida.model.user.User with id 56
org.springframework.orm.jpa.JpaObjectRetrievalFailureException: Unable to find ca.corefacility.bioinformatics.irida.model.user.User with id 56; nested exception is javax.persistence.EntityNotFoundException: Unable to find ca.corefacility.bioinformatics.irida.model.user.User with id 56
	at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:379)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:257)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:528)
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:153)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:178)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy209.findRevisions(Unknown Source)
	at ca.corefacility.bioinformatics.irida.ria.web.analysis.auditing.AnalysisAudit.getAnalysisRunningTime(AnalysisAudit.java:41)
	at ca.corefacility.bioinformatics.irida.ria.web.analysis.AnalysesTableAjaxController.createAnalysisModel(AnalysesTableAjaxController.java:228)
...
	at ca.corefacility.bioinformatics.irida.model.user.User$HibernateProxy$p264HidX.hashCode(Unknown Source)
	at java.base/java.util.Arrays.hashCode(Arrays.java:4685)
	at java.base/java.util.Objects.hash(Objects.java:146)
	at ca.corefacility.bioinformatics.irida.model.workflow.submission.AnalysisSubmission.hashCode(AnalysisSubmission.java:546)
	at org.hibernate.envers.internal.tools.Triple.hashCode(Triple.java:63)
	at java.base/java.util.HashMap.hash(HashMap.java:339)
	at java.base/java.util.HashMap.put(HashMap.java:607)
	at org.hibernate.envers.internal.reader.FirstLevelCache.putOnEntityNameCache(FirstLevelCache.java:87)
	at org.hibernate.envers.internal.entities.EntityInstantiator.createInstanceFromVersionsEntity(EntityInstantiator.java:100)
	at org.hibernate.envers.internal.entities.EntityInstantiator.addInstancesFromVersionsEntities(EntityInstantiator.java:153)
	at org.hibernate.envers.query.internal.impl.AbstractAuditQuery.applyProjections(AbstractAuditQuery.java:341)
	at org.hibernate.envers.query.internal.impl.EntitiesAtRevisionQuery.list(EntitiesAtRevisionQuery.java:133)
	at org.hibernate.envers.query.internal.impl.AbstractAuditQuery.getSingleResult(AbstractAuditQuery.java:116)
	at org.hibernate.envers.internal.reader.AuditReaderImpl.find(AuditReaderImpl.java:121)
	at org.springframework.data.envers.repository.support.EnversRevisionRepositoryImpl.getEntitiesForRevisions(EnversRevisionRepositoryImpl.java:193)
	at org.springframework.data.envers.repository.support.EnversRevisionRepositoryImpl.findRevisions(EnversRevisionRepositoryImpl.java:135)
...
```

The way this presents itself is similar to https://github.com/phac-nml/irida/issues/1004, but it has a different cause.

## Steps to reproduce the problem
What were you doing when you encountered the problem?
1. Log into IRIDA.
2. Try to go to **Analyses > Your Analyses**
3. The page crashes.

## Expected behaviour
I expected the page to successfully load.

## Additional context
None.

**Comment by apetkau** [comment]
To clarify about `hashCode()` and `equals()`, the issues that happen when overriding these methods for mutable objects occurs when you use the object (an instance of `AnalysisSubmission`) as a *key* in a hash table or add to any other hash data structure (e.g., a `HashSet`) and then modify the object and try to look it up in the data structure again. If this doesn't happen, then there shouldn't be issues with overriding `hashCode()` and `equals()`.

I don't think this is the actual source of the issue, it looks more like something is wrong with the particular IRIDA database in question.

**Comment by tom114** [comment]
Closing as it appears the issue in this case was with an inconsistent database state causing problems with Envers.
