### ISSUE TITLE
A "Remote IRIDA Connection" cannot be deleted if there is a synchronized project associated with it.

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#108]
If I attempt to remove a **Remote IRIDA Connection** with an associated synchronized project (by clicking **Remove** button below, an exception is thrown.

![Screenshot_from_2017-08-29_13-20-43](/uploads/ff143093dfb7894ddb90322a8eb232ec/Screenshot_from_2017-08-29_13-20-43.png)

```
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: 29 Aug 2017 13:23:06,649 ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper:146 - Cannot delete or update a parent row: a foreign key constraint fails (`irida_web_development`.`remote_status`, CONSTRAIN
T `FK_REMOTE_STATUS_API` FOREIGN KEY (`api_id`) REFERENCES `remote_api` (`id`))
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: 29 Aug 2017 13:23:06,652 ERROR ca.corefacility.bioinformatics.irida.ria.web.errors.ExceptionHandlerController:117 - could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hiberna
te.exception.ConstraintViolationException: could not execute statement
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execut
e statement
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:259)
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:225)
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:521)
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:761)
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:730)
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:485)
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:291)
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
...
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`irida_web_development`.`remote_status`, CONSTRAI
NT `FK_REMOTE_STATUS_API` FOREIGN KEY (`api_id`) REFERENCES `remote_api` (`id`))
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: at com.mysql.jdbc.Util.handleNewInstance(Util.java:408)
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: at com.mysql.jdbc.Util.getInstance(Util.java:383)
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1049)
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4226)
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4158)
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2615)
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2776)
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2840)
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2082)
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2334)
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2262)
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2246)
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:98)
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:98)
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:208)
Aug 29 13:23:06 irida-web-development.corefacility.ca server[26359]: ... 109 more
```

Imported from GitLab issue #528.  Originally posted on 2017/08/29 01:23PM

**Comment by tom114** [comment]
I would suggest this isn't actually a bug, and that the remote connection should not be able to be deleted.  The UI should handle it better though instead of dying like that.
