### ISSUE TITLE
Cannot use IRIDA with newer versions of Galaxy

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#1401]
## Describe the bug

Attempting to run a pipeline through IRIDA with newer versions of Galaxy (22.05) fails with the following exception:

```
java.lang.NullPointerException: Unknown state deferred
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907) ~[guava-31.0.1-jre.jar:na]
        at ca.corefacility.bioinformatics.irida.model.workflow.execution.galaxy.GalaxyWorkflowState.stringToState(GalaxyWorkflowState.java:60) ~[classes/:na]
        at ca.corefacility.bioinformatics.irida.model.workflow.execution.galaxy.GalaxyWorkflowStatus$GalaxyWorkflowStatusBuilder.createStateIdsMap(GalaxyWorkflowStatus.java:194) ~[classes/:na]
        at ca.corefacility.bioinformatics.irida.model.workflow.execution.galaxy.GalaxyWorkflowStatus$GalaxyWorkflowStatusBuilder.build(GalaxyWorkflowStatus.java:172) ~[classes/:na]
        at ca.corefacility.bioinformatics.irida.pipeline.upload.galaxy.GalaxyHistoriesService.getStatusForHistory(GalaxyHistoriesService.java:111) ~[classes/:na]
        at ca.corefacility.bioinformatics.irida.service.analysis.execution.galaxy.AnalysisExecutionServiceGalaxy.getWorkflowStatus(AnalysisExecutionServiceGalaxy.java:138) ~[classes/:na]
        at ca.corefacility.bioinformatics.irida.service.impl.AnalysisExecutionScheduledTaskImpl.monitorRunningAnalyses(AnalysisExecutionScheduledTaskImpl.java:177)
~[classes/:na]
        at ca.corefacility.bioinformatics.irida.config.services.scheduled.AnalysisScheduledTaskConfig.monitorRunningAnalyses(AnalysisScheduledTaskConfig.java:90) ~[classes/:na]
...
```

## Steps to reproduce the problem
What were you doing when you encountered the problem?
1. Connect IRIDA to Galaxy 22.05
2. Run a pipeline
3. The pipeline will fail with the above exception

## Expected behaviour
I expected the pipeline to succeed.

## Additional context
None.

**Comment by ericenns** [comment]
Fixed in #1402
