### ISSUE TITLE
Uploading many sequence files to NCBI times out

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#141]
Users who are uploading large batches of sequence files to NCBI keep on encountering a connection timeout.  The exceptions look like:

```
15 Feb 2018 17:52:57,978 ERROR ca.corefacility.bioinformatics.irida.service.export.ExportUploadService:577 - Error uploading file: 150 Opening BINARY mode data connection for 56437.fastq

org.apache.commons.net.io.CopyStreamException: IOException caught while copying.
        at org.apache.commons.net.io.Util.copyStream(Util.java:134)
        at org.apache.commons.net.ftp.FTPClient._storeFile(FTPClient.java:653)
        at org.apache.commons.net.ftp.FTPClient.__storeFile(FTPClient.java:624)
        at org.apache.commons.net.ftp.FTPClient.storeFile(FTPClient.java:1976)
        at ca.corefacility.bioinformatics.irida.service.export.ExportUploadService.uploadPath(ExportUploadService.java:572)
        at ca.corefacility.bioinformatics.irida.service.export.ExportUploadService.uploadSubmission(ExportUploadService.java:288)
        at ca.corefacility.bioinformatics.irida.service.export.ExportUploadService.launchUpload(ExportUploadService.java:143)
        at ca.corefacility.bioinformatics.irida.config.services.IridaScheduledTasksConfig.ncbiUpload(IridaScheduledTasksConfig.java:147)
        at sun.reflect.GeneratedMethodAccessor741.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.security.concurrent.DelegatingSecurityContextRunnable.run(DelegatingSecurityContextRunnable.java:57)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Connection timed out
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:95)
        at org.apache.commons.net.io.ToNetASCIIOutputStream.write(ToNetASCIIOutputStream.java:80)
        at org.apache.commons.net.io.Util.copyStream(Util.java:111)
        ... 20 more
```

Imported from GitLab issue #611.  Originally posted on 2018/02/16 08:20AM

**Comment by tom114** [comment]
The NCBI upload code has been drastically sped up by #452 and the retry mechanism we've built in improves stability.  While there are still occasional hiccups uploading to NCBI, I'm closing this since it's original intent is mostly fixed.
