### ISSUE TITLE
Synchronizing projects with metadata does not work

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#222]
In our latest `development` branch, if I try to sync a project where samples have metadata assigned (e.g., derived from a pipeline) I will get the following exception:

```
14 Dec 2018 13:40:06,639 DEBUG ca.corefacility.bioinformatics.irida.service.remote.ProjectSynchronizationService:151 - An error occurred while synchronizing project http://localhost:8080/api/projects/3
org.springframework.orm.ObjectRetrievalFailureException: Object [id=null] was not of the specified subclass [ca.corefacility.bioinformatics.irida.model.sample.metadata.MetadataEntry] : class of the given object did not match class of persistent copy; nested exception is org.
hibernate.WrongClassException: Object [id=null] was not of the specified subclass [ca.corefacility.bioinformatics.irida.model.sample.metadata.MetadataEntry] : class of the given object did not match class of persistent copy
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:294)
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:225)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:417)
        at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:59)
        at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:213)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:147)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodIntercceptor.invoke(CrudMethodMetadataPostProcessor.java:111)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
        at com.sun.proxy.$Proxy161.save(Unknown Source)
        at ca.corefacility.bioinformatics.irida.service.impl.CRUDServiceImpl.update(CRUDServiceImpl.java:223)
        at ca.corefacility.bioinformatics.irida.service.impl.sample.SampleServiceImpl.update(SampleServiceImpl.java:172)
        at ca.corefacility.bioinformatics.irida.service.impl.sample.SampleServiceImpl.update(SampleServiceImpl.java:67)
        at ca.corefacility.bioinformatics.irida.service.impl.sample.SampleServiceImpl$$FastClassBySpringCGLIB$$9792ab2e.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:718)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:64)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:654)
        at ca.corefacility.bioinformatics.irida.service.impl.sample.SampleServiceImpl$$EnhancerBySpringCGLIB$$89119358.update(<generated>)
        at ca.corefacility.bioinformatics.irida.service.remote.ProjectSynchronizationService.syncSample(ProjectSynchronizationService.java:287)
        at ca.corefacility.bioinformatics.irida.service.remote.ProjectSynchronizationService.syncProject(ProjectSynchronizationService.java:243)
        at ca.corefacility.bioinformatics.irida.service.remote.ProjectSynchronizationService.findMarkedProjectsToSync(ProjectSynchronizationService.java:143)
        at ca.corefacility.bioinformatics.irida.config.services.scheduled.ProjectSyncScheduledTaskConfig.syncProject(ProjectSyncScheduledTaskConfig.java:27)
...
```

**Comment by apetkau** [comment]
This could have been introduced in https://github.com/phac-nml/irida/pull/216. I'll check it out.

**Comment by apetkau** [comment]
So far it seems to all be working in `master` (and with release `0.22.5`), so maybe not introduced by my previous fix.

**Comment by apetkau** [comment]
Attempting to sync a project with uploaded metadata (not pipeline-derived) also gives me an error:

```
18 Dec 2018 14:47:09,098 ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper:146 - Duplicate entry '10' for key 'UK_SAMPLE_METADATA_ENTRY'
18 Dec 2018 14:47:09,126 DEBUG ca.corefacility.bioinformatics.irida.service.remote.ProjectSynchronizationService:154 - An error occurred while synchronizing project http://localhost:8080/api/projects/3
org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [UK_SAMPLE_METADATA_ENTRY]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:259)
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:225)
        at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:521)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:761)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:730)
...
```

This only occurs in the `development` branch.
