### ISSUE TITLE
irida

### ISSUE THREAD

**Issue by happykhan** [phac-nml/irida#224]
Hi, 

I've been trying to config the irida importer for a while. It doesn't seem to honour the irida_url. It runs final linking to irida (get from irida in galaxy). It then, seems to be fine when it comes back into galaxy. But final fetch Galaxy > irida always seems to pull from localhost, even though its overridden in config (below). Yes I've run irida_importer.py -- config && restart galaxy daemons. 

```
[Galaxy]

admin_key: xxxxxxxxxxxxxxxxxxxxxxx
galaxy_url: http://<not localhost!>/galaxy/
illumina_path: /illumina_reads
reference_path: /references
xml_file: irida_import.xml
max_waits: 120

[IRIDA]

client_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
token_endpoint_suffix: /api/oauth/token

# Be sure to run the tool with the '--config' option and then to restart Galaxy after changing these values!
client_id: default
irida_url: http://<not localhost!>/irida
initial_endpoint_suffix: /projects


```

I've had to add a dirty hack in irida_importer.py to force it to work. 

```

 def make_irida_request(self, request_url):
        """
        Requests json object from IRIDA REST API.

        :type request_url: str
        :param request_url: a url to make a get request to. See IRIDA REST API
        docs for more information
        :return: a list of either single output samples(string) or paired
        output samples(tuple)
        """
        request_url = request_url.replace('http://127.0.0.1:8080/', 'http://<my-ip>/')
        response = self.irida.get(request_url)

        # Raise an exception if we get 4XX or 5XX server response
        response.raise_for_status()

        resource = response.json()['resource']
        self.logger.debug("The JSON parameters from the IRIDA API are:\n" +
                          self.pp.pformat(json.dumps(dict(resource), indent=2)))

        return resource

```

**Comment by happykhan** [comment]
Double checked by grabbing the irida_url at runtime. Definitely not local host, yet it still wants to route requests that way. Not sure if URL is encoded in token, or galaxy job elsewhere??


```
python /home/galaxy/shed_tools/irida.corefacility.ca/galaxy-shed/repos/aaron/irida_galaxy_importer/6dcc8b354392/irida_galaxy_importer/irida_import.py --json_parameter_file "/export/galaxy/database/files/000/dataset_223.dat" --log-file /export/galaxy/database/files/000/dataset_222.dat -t 5f789c18-bfc8-4574-aefe-5e868df2c927
http://<NOT LOCALHOST>/irida
Importing files from IRIDA to Galaxy...
{'access_token': '5f789c18-bfc8-4574-aefe-5e868df2c927'}
Import failed.
Final summary:
0 file(s) imported and 0 file(s) skipped.
Traceback (most recent call last):
  File "/home/galaxy/shed_tools/irida.corefacility.ca/galaxy-shed/repos/aaron/irida_galaxy_importer/6dcc8b354392/irida_galaxy_importer/irida_import.py", line 813, in <module>
    token=args.token)
  File "/home/galaxy/shed_tools/irida.corefacility.ca/galaxy-shed/repos/aaron/irida_galaxy_importer/6dcc8b354392/irida_galaxy_importer/irida_import.py", line 732, in import_to_galaxy
    samples = self.get_samples(samples_dict)
  File "/home/galaxy/shed_tools/irida.corefacility.ca/galaxy-shed/repos/aaron/irida_galaxy_importer/6dcc8b354392/irida_galaxy_importer/irida_import.py", line 74, in get_samples
    paired_resource = self.make_irida_request(sample.paired_path)
  File "/home/galaxy/shed_tools/irida.corefacility.ca/galaxy-shed/repos/aaron/irida_galaxy_importer/6dcc8b354392/irida_galaxy_importer/irida_import.py", line 111, in make_irida_request
    response.raise_for_status()
  File "/home/galaxy/galaxy/.venv/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://127.0.0.1:8080/irida/api/samples/4/pairs

```

**Comment by apetkau** [comment]
Thanks @happykhan for reporting the issue.

I've been doing a bit of testing on my own machine and it's all working for me.  But, I think I may have a clue as to why this is occurring. Is the IRIDA instance you are hosting behind a proxy server?

The specific line that is giving the error is https://github.com/phac-nml/irida-galaxy-importer/blob/544cfe6af93c177fac60fefc7ca35ad7ec1fb5f5/irida_import/irida_import.py#L76, which is requesting more information about files stored in IRIDA from a URL returned by the REST API. So, the importer tool should have already contacted IRIDA once successfully (with the correct URL) and is now contacting again with URLs returned by the API.  If there is a proxy server in the middle, IRIDA may be returning `127.0.0.1:8080` as the URL, since this is where it's currently serving under.  For apache, you can preserve the original host name with [ProxyPreserveHost](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypreservehost).

Alternatively, if there's no proxy server used, there may be some weird config issue with Tomcat, where it's not recognizing the proper public-facing hostname (and so filling in `127.0.0.1:8080` as the URL in the IRIDA API).

**Comment by happykhan** [comment]
Yes.

I have nginx (reverse proxy)  set up

**Comment by apetkau** [comment]
Okay, great. That makes sense then.

So, I *think* it's specifically the `X-Forwarded-Host` header that has to be set in nginx, which can be done with `proxy_set_header` (http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header). For example:

```
    location /irida {
        proxy_pass          http://localhost:8080;
        proxy_set_header    X-Forwarded-Host $host;
    }
```

@ericenns or @Takadonet would this be the correct header to set?
