### ISSUE TITLE
Cannot support duplicate tool in Galaxy workflow

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#285]
## Describe the bug

For an IRIDA Galaxy workflow duplicate tools in the same workflow do not appear to be supported.

## Steps to reproduce the problem

Create a workflow with multiple copies of the same tool. When trying to run the workflow, the following exception will be produced:

```
Feb 19 20:52:43 v0886.nbi.ac.uk server[16373]: java.lang.IllegalArgumentException: parameterMap already contains key with name "db" mapping to value "vfdb"
Feb 19 20:52:43 v0886.nbi.ac.uk server[16373]: at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125)
Feb 19 20:52:43 v0886.nbi.ac.uk server[16373]: at ca.corefacility.bioinformatics.irida.service.analysis.workspace.galaxy.ParameterBuilderGalaxy.insertToMapRecursive(ParameterBuilderGalaxy.java:161
Feb 19 20:52:43 v0886.nbi.ac.uk server[16373]: at ca.corefacility.bioinformatics.irida.service.analysis.workspace.galaxy.ParameterBuilderGalaxy.addParameter(ParameterBuilderGalaxy.java:132)
Feb 19 20:52:43 v0886.nbi.ac.uk server[16373]: at ca.corefacility.bioinformatics.irida.service.analysis.workspace.galaxy.AnalysisParameterServiceGalaxy.prepareAnalysisParameters(AnalysisParameterS
Feb 19 20:52:43 v0886.nbi.ac.uk server[16373]: at ca.corefacility.bioinformatics.irida.service.analysis.workspace.galaxy.AnalysisWorkspaceServiceGalaxy.prepareAnalysisFiles(AnalysisWorkspaceServic
Feb 19 20:52:43 v0886.nbi.ac.uk server[16373]: at ca.corefacility.bioinformatics.irida.service.analysis.execution.galaxy.AnalysisExecutionServiceGalaxyAsync.executeAnalysis(AnalysisExecutionServic
```

## Expected behaviour

I would expect the ability to support duplicate tools in the same workflow.

## Additional context

None.

**Comment by apetkau** [comment]
Duplicate of https://github.com/phac-nml/irida/issues/425
