### ISSUE TITLE
UploadErrorException while running SNVPhyl

### ISSUE THREAD

**Issue by glwinsor** [phac-nml/irida#54]
The upload tool was throwing a lot of exceptions in production when using the local runner so I switched it to use the slurm runner. That cleared up a lot of the problems, however this exception was thrown from the IRIDA web app today:

```
01 Oct 2018 12:31:12,147 ERROR ca.corefacility.bioinformatics.irida.service.analysis.execution.AnalysisExecutionServiceAspect:63 - Error occured for submission: AnalysisSubmission [id=1297, name=SNVPhyl_20181001, submitter=redacted, workflowId=b7c8b437-3c41-485e-92e5-72b67e37959f, analysisState=SUBMITTING, analysisCleanedState=NOT_CLEANED] changing to state ERROR
ca.corefacility.bioinformatics.irida.exceptions.UploadErrorException: Error: upload to Galaxy library id=35873d405cae18ea name=AnalysisSubmission-78d95984-e9c6-4229-b19d-48208108db40 for dataset id=38c9a36f2a239f84 name=ECL19894_S12_L001_R1_001.fastq failed with state=error
        at ca.corefacility.bioinformatics.irida.pipeline.upload.galaxy.GalaxyLibrariesService$1.call(GalaxyLibrariesService.java:231)
        at ca.corefacility.bioinformatics.irida.pipeline.upload.galaxy.GalaxyLibrariesService$1.call(GalaxyLibrariesService.java:209)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

The galaxy logs show the following:

```
galaxy.jobs.runners.slurm ERROR 2018-10-01 12:23:51,532 (22347/12234799) Failure in SLURM _complete_terminal_job(), job final state will be: 
failed
Traceback (most recent call last):
  File "/project/6004808/irida/galaxy-17.09/lib/galaxy/jobs/runners/slurm.py", line 81, in _complete_terminal_job
    slurm_state = _get_slurm_state()
  File "/project/6004808/irida/galaxy-17.09/lib/galaxy/jobs/runners/slurm.py", line 71, in _get_slurm_state
    job_state = _get_slurm_state_with_sacct(job_id, cluster)
  File "/project/6004808/irida/galaxy-17.09/lib/galaxy/jobs/runners/slurm.py", line 47, in _get_slurm_state_with_sacct
    raise Exception('`%s` returned %s, stderr: %s' % (' '.join(cmd), p.returncode, stderr))
Exception: `sacct -n -o state -j 12234799` returned 1, stderr: sacct: error: slurm_persist_conn_open_without_init: failed to open persistent 
connection to slurmdb:6819: No route to host
sacct: error: slurmdbd: Sending PersistInit msg: No route to host
sacct: error: Problem talking to the database: No route to host

```

This suggests that the problem was with our slurm scheduler not being available. Unfortunately, there are no error messages on the analysis details page. Would it be possible to get some kind of message describing this error returned to the user?

**Comment by apetkau** [comment]
I can look into this. See also comment at https://github.com/phac-nml/irida/issues/55#issuecomment-426680074
