### ISSUE TITLE
SNVPhyl analysis being marked as failed.

### ISSUE THREAD

**Issue by glwinsor** [phac-nml/irida#55]
I'm seeing this exception being thrown in the web application error log while running the SNVPhyl pipline:

```
02 Oct 2018 06:28:19,229 ERROR ca.corefacility.bioinformatics.irida.service.impl.AnalysisExecutionScheduledTaskImpl:263 - Workflow for analysis AnalysisSubmission [id=1298, name=SNVPhyl_20181002, submitter=redacted, workflowId=b7c8b437-3c41-485e-92e5-72b67e37959f, analysisState=RUNNING, analysisCleanedState=NOT_CLEANED] in error state WorkflowStatus [state=running, percentComplete=0.2513181]
02 Oct 2018 06:28:19,709 ERROR ca.corefacility.bioinformatics.irida.service.impl.AnalysisExecutionScheduledTaskImpl:174 - Error checking state for AnalysisSubmission [id=1298, name=SNVPhyl_20181002, submitter=redacted, workflowId=b7c8b437-3c41-485e-92e5-72b67e37959f, analysisState=ERROR, analysisCleanedState=NOT_CLEANED]
java.lang.NullPointerException
        at ca.corefacility.bioinformatics.irida.model.workflow.analysis.JobError.<init>(JobError.java:164)
        at ca.corefacility.bioinformatics.irida.pipeline.upload.galaxy.GalaxyJobErrorsService.createNewJobErrors(GalaxyJobErrorsService.java:60)
        at ca.corefacility.bioinformatics.irida.service.impl.AnalysisExecutionScheduledTaskImpl.handleJobErrors(AnalysisExecutionScheduledTaskImpl.java:191)
        at ca.corefacility.bioinformatics.irida.service.impl.AnalysisExecutionScheduledTaskImpl.handleWorkflowStatus(AnalysisExecutionScheduledTaskImpl.java:266)
        at ca.corefacility.bioinformatics.irida.service.impl.AnalysisExecutionScheduledTaskImpl.monitorRunningAnalyses(AnalysisExecutionScheduledTaskImpl.java:172)
        at ca.corefacility.bioinformatics.irida.config.services.scheduled.AnalysisScheduledTaskConfig.monitorRunningAnalyses(AnalysisScheduledTaskConfig.java:82)
        at sun.reflect.GeneratedMethodAccessor438.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.security.concurrent.DelegatingSecurityContextRunnable.run(DelegatingSecurityContextRunnable.java:57)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
02 Oct 2018 06:49:54,718 DEBUG ca.corefacility.bioinformatics.irida.ria.web.LoginController:66 - Displaying login page.

```

I'm pretty sure it's stemming from problems with slurm and related to this previous issue https://github.com/phac-nml/irida/issues/54:

```
galaxy.jobs.runners.drmaa DEBUG 2018-10-02 09:45:09,919 (23115/12263563) state change: job finished, but failed
galaxy.jobs.runners.slurm ERROR 2018-10-02 09:45:17,746 (23115/12263563) Failure in SLURM _complete_terminal_job(), job final state will be: failed
```
and more error log output here:

```
sacct: error: slurmdbd: Sending PersistInit msg: No route to host
sacct: error: Problem talking to the database: No route to host
galaxy.jobs.runners.drmaa DEBUG 2018-10-02 09:36:46,888 (22974/12263368) state change: job finished, but failed
galaxy.jobs.runners.drmaa WARNING 2018-10-02 09:36:56,886 (22969) drmaa.Session.runJob() failed, will retry: code 1: slurm_submit_batch_job: Unspecifie
d error
galaxy.jobs.runners.slurm ERROR 2018-10-02 09:37:01,337 (22974/12263368) Failure in SLURM _complete_terminal_job(), job final state will be: failed
Traceback (most recent call last):
  File "/project/6004808/irida/galaxy-17.09/lib/galaxy/jobs/runners/slurm.py", line 81, in _complete_terminal_job
    slurm_state = _get_slurm_state()
  File "/project/6004808/irida/galaxy-17.09/lib/galaxy/jobs/runners/slurm.py", line 71, in _get_slurm_state
    job_state = _get_slurm_state_with_sacct(job_id, cluster)
  File "/project/6004808/irida/galaxy-17.09/lib/galaxy/jobs/runners/slurm.py", line 47, in _get_slurm_state_with_sacct
    raise Exception('`%s` returned %s, stderr: %s' % (' '.join(cmd), p.returncode, stderr))
Exception: `sacct -n -o state -j 12263368` returned 1, stderr: sacct: error: slurm_persist_conn_open_without_init: failed to open persistent connection
 to slurmdb:6819: No route to host
sacct: error: slurmdbd: Sending PersistInit msg: No route to host
sacct: error: Problem talking to the database: No route to host
galaxy.jobs.runners.drmaa DEBUG 2018-10-02 09:37:04,820 (22976/12263372) state change: job finished, but failed
galaxy.jobs.runners.drmaa WARNING 2018-10-02 09:37:15,578 (22969) drmaa.Session.runJob() failed, will retry: code 1: slurm_submit_batch_job: Unspecifie
d error
galaxy.jobs.runners.slurm ERROR 2018-10-02 09:37:15,645 (22976/12263372) Failure in SLURM _complete_terminal_job(), job final state will be: failed
```

There are a lot of these exceptions being thrown in the galaxy error log (due to some major downtime on the cluster) but I can't find any failed jobs when I log in to view the workflow in Galaxy.  I'm assuming Galaxy is resubmitting them but IRIDA detected an error along the way and marked the analysis_submission as failed? Is there a way to make it more robust on the web application side? Or at least have some of the error show up on the analysis details page on IRIDA?

**Comment by apetkau** [comment]
Hello Geoff,

The error appears to be from this line of code https://github.com/galaxyproject/galaxy/blob/v17.09/lib/galaxy/jobs/runners/slurm.py#L47, which is getting called from https://github.com/galaxyproject/galaxy/blob/v17.09/lib/galaxy/jobs/runners/slurm.py#L81.

This code is triggered when the **drmaa** states is **FAILED** and it looks like Galaxy is trying to pull out the SLURM job state in this case. This is done by first running the `scontrol -o show job [job id]` SLURM command, and if this fails it will try the `sacct -n -o state -j [job id]` command.  It looks like the `sacct` is failing (I assume due to the downtime on your cluster).

For why it will show up as failed in IRIDA but not Galaxy, I'm not sure yet. I'll have to look into this. It could be related to how we have previously configured Galaxy to attempt to resubmit the job in case of some SLURM failures, but maybe some failed message is getting sent back to IRIDA in that case.  I will have to take a more detailed look at this issue.

I can also add an issue to improve error reporting in the IRIDA UI.

**Comment by glwinsor** [comment]
Thanks @apetkau 

A lot of jobs on Cedar returned NODE_FAIL and CANCELLED so I don't know if IRIDA can handle these codes, can it?

I contacted Cedar support and they say they've been experiencing a lot of issues between September 18th until yesterday.  They're also expecting an outage on Oct 15-19 while they perform OS updates, file system upgrades and other modification so we'll have to post a notice somewhere to tell users to expect it. 

The extra error info would be helpful. Perhaps a little help doc to help interpret the messages may be good as well. For example, some failed jobs are out of IRIDA's control and it would make sense to just submit again. BTW, it would be a nice feature to be able to resubmit failed jobs directly from the page showing the list of analyses that have completed/failed. Thus, if a job fails, the person could click on a button next to it to resubmit. Is that possible?

**Comment by apetkau** [comment]
These states are all handled by Galaxy. It looks like those two `NODE_FAIL` and `CANCELLED` are both handled https://github.com/galaxyproject/galaxy/blob/v17.09/lib/galaxy/jobs/runners/slurm.py#L101.

Do you mean a doc on interpreting messages when it comes to issues with Galaxy/SLURM?  I could try to write up a little more details on this. There's also a nice search feature through the Galaxy docs/support forms at https://galaxyproject.org/, though I didn't find much on your particular issue.

Being able to resubmit failed jobs from IRIDA is on our list of issues. I can take a look into it when I have time.

**Comment by glwinsor** [comment]
Thanks Aaron, 

I guess I was thinking that in addition to any raw error message that might be returned, we could get the point across that sometimes you just need to try resubmitting the job again.

re: resubmission of jobs, it would definitely helpful to be able to do this.

**Comment by apetkau** [comment]
Ah, okay. I understand @glwinsor. Yes, we can try to detect situations where a user may need to try and resubmit a job and warn them about it (or try again internally in IRIDA).
