### ISSUE TITLE
Sequence upload step failing at FastQC analysis

### ISSUE THREAD

**Issue by glwinsor** [phac-nml/irida#651]
HI all,

We're  setting up a new environment based on IRIDA 20.01.2 and Galaxy 19.05. 

I wanted to test a simple situation where a person creates a project with one sample and uploads a pair of fastq files.

I created a project with one sample and uploaded two fastq files. Files appear uploaded but an exception is thrown when the applications attempts to run fastqc analysis on them. The same exception is thrown if I set up a remote connection and synchronize a project metadata, samples and fastq files. 

When I click on one of the uploaded sequence files, get a message saying "A fastQC analysis has not been performed on this file."

## The full error log output:
```
        at ca.corefacility.bioinformatics.irida.processing.impl.DefaultFileProcessingChain.launchChain(DefaultFileProcessingChain.java:83)
        at ca.corefacility.bioinformatics.irida.service.impl.processor.SequenceFileProcessorLauncher.run(SequenceFileProcessorLauncher.java:45)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "fileProcessingChainExecutor-56" java.lang.NoClassDefFoundError: Could not initialize class javax.swing.RepaintManager
        at java.desktop/javax.swing.JComponent.repaint(JComponent.java:4835)
        at java.desktop/java.awt.Component.repaint(Component.java:3394)
        at java.desktop/javax.swing.JComponent.setUI(JComponent.java:690)
        at java.desktop/javax.swing.JPanel.setUI(JPanel.java:150)
        at java.desktop/javax.swing.JPanel.updateUI(JPanel.java:126)
        at java.desktop/javax.swing.JPanel.<init>(JPanel.java:86)
        at java.desktop/javax.swing.JPanel.<init>(JPanel.java:109)
        at java.desktop/javax.swing.JPanel.<init>(JPanel.java:117)
        at uk.ac.babraham.FastQC.Graphs.QualityBoxPlot.<init>(QualityBoxPlot.java:51)
        at uk.ac.babraham.FastQC.Modules.PerBaseQualityScores.getResultsPanel(PerBaseQualityScores.java:53)
        at ca.corefacility.bioinformatics.irida.processing.impl.FastqcFileProcessor.handlePerBaseQualityScores(FastqcFileProcessor.java:160)
        at ca.corefacility.bioinformatics.irida.processing.impl.FastqcFileProcessor.processSingleFile(FastqcFileProcessor.java:114)
        at ca.corefacility.bioinformatics.irida.processing.impl.FastqcFileProcessor.process(FastqcFileProcessor.java:75)
        at ca.corefacility.bioinformatics.irida.processing.impl.FastqcFileProcessor$$FastClassBySpringCGLIB$$c93e547.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
        at ca.corefacility.bioinformatics.irida.processing.impl.FastqcFileProcessor$$EnhancerBySpringCGLIB$$d7f904cb.process(<generated>)
        at ca.corefacility.bioinformatics.irida.processing.impl.DefaultFileProcessingChain.launchChain(DefaultFileProcessingChain.java:83)
        at ca.corefacility.bioinformatics.irida.service.impl.processor.SequenceFileProcessorLauncher.run(SequenceFileProcessorLauncher.java:45)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

```

I'm not clear on the expected behaviour. I assume the fastqc analysis is handled by Galaxy but I don't see any activity in it's log. I can't tell from the above error if it's something configured wrong on the galaxy side or not.

War was built from source using openjdk version 11.03 and 13.0.1 and we get the same error output in both cases.

Thanks

**Comment by apetkau** [comment]
Hello @glwinsor. fastqc is run directly within IRIDA, it's not run via Galaxy.

I do not know why you are getting that exact issue. One thing I can think of for you to try is to add

```
-Djava.awt.headless=true
```

To the `JAVA_OPTS` config parameter for Tomcat (same place you modify to set the Spring profile, https://irida.corefacility.ca/documentation/administrator/web/#servlet-container-configuration).

The reason I'm thinking of this is that it informs Java that the machine you are running everything on has no attached monitor/keyboard/mouse. This stops Java from trying to load up some libraries. Maybe this is causing an issue (since FastQC, when run in standalone mode, has a built-in UI for displaying sequence quality information).

**Comment by glwinsor** [comment]
Hi @apetkau thanks for the suggestion. It worked! I'm surprised it had to be added to JAVA_OPTS since it doesn't appear to be specified in any of our earlier versions.  Thanks again!

**Comment by apetkau** [comment]
No problem @glwinsor. It's possible it worked in earlier versions if IRIDA happened to be running on a machine that already had a graphical system installed (e.g., X server and window manager). In that case, the graphics libraries that fastqc is trying to load up will be found and it will succeed. If, now, you are running IRIDA on a system without an X server, it may now be failing since some of those graphics libraries aren't found (but setting `-Djava.awt.headless=true` tells Java you don't need them).

At least, that's what I think, but I don't know all the details on how Java handles loading up libraries for native UI/graphics.
