### ISSUE TITLE
Assembly annotation pipeline fails with Galaxy 20.01

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#669]
## Describe the bug

If running IRIDA against Galaxy 20.01 the Assembly and annotation pipeline will fail. In IRIDA the message is:

```
30 Apr 2020 08:15:59,513 ERROR ca.corefacility.bioinformatics.irida.service.analysis.execution.AnalysisExecutionServiceAspect:65 - Error occured for submission: AnalysisSubmission [id=17, name=AssemblyAnnotation_20200430_hcc23, submitter=admin, workflo
wId=4673cf14-20eb-44e1-986b-ac7714f9a96f, analysisState=SUBMITTING, analysisCleanedState=NOT_CLEANED] changing to state ERROR
ca.corefacility.bioinformatics.irida.exceptions.WorkflowException: GalaxyResponseException{status=500, responseBody={"err_msg"
: "Uncaught exception in exposed API method:", "err_code": 0}, errorMessage=Uncaught exception in exposed API method:, errorCo
de=0, traceback=null}
        at ca.corefacility.bioinformatics.irida.pipeline.upload.galaxy.GalaxyWorkflowService.runWorkflow(GalaxyWorkflowService
.java:123)
        at ca.corefacility.bioinformatics.irida.service.analysis.execution.galaxy.AnalysisExecutionServiceGalaxyAsync.executeAnalysis(AnalysisExecutionServiceGalaxyAsync.java:152)
        at ca.corefacility.bioinformatics.irida.service.analysis.execution.galaxy.AnalysisExecutionServiceGalaxyAsync$$FastClassBySpringCGLIB$$fc2d896.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
...

Caused by: GalaxyResponseException{status=500, responseBody={"err_msg": "Uncaught exception in exposed API method:", "err_code": 0}, errorMessage=Uncaught exception in exposed API method:, errorCode=0, traceback=null}
        at com.github.jmchilton.blend4j.galaxy.Client.buildResponseException(Client.java:18)
        at com.github.jmchilton.blend4j.BaseClient.checkResponse(BaseClient.java:138)
        at com.github.jmchilton.blend4j.BaseClient.create(BaseClient.java:47)
        at com.github.jmchilton.blend4j.BaseClient.create(BaseClient.java:36)
        at com.github.jmchilton.blend4j.BaseClient.create(BaseClient.java:32)
        at com.github.jmchilton.blend4j.galaxy.WorkflowsClientImpl.runWorkflowResponse(WorkflowsClientImpl.java:38)
        at com.github.jmchilton.blend4j.galaxy.WorkflowsClientImpl.runWorkflow(WorkflowsClientImpl.java:42)
        at ca.corefacility.bioinformatics.irida.pipeline.upload.galaxy.GalaxyWorkflowService.runWorkflow(GalaxyWorkflowService.java:121)
```

In Galaxy the message is:

```
galaxy.workflow.run ERROR 2020-04-30 08:15:59,492 [p:51155,w:1,m:0] [uWSGIWorker1Core2] Failed to schedule Workflow[id=10,name=AssemblyAnnotation-shovill-prokka-quast-paired_reads-v0.5], problem occurred on WorkflowStep[index=2,type=tool].
Traceback (most recent call last):
  File "lib/galaxy/workflow/run.py", line 190, in invoke
  incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "lib/galaxy/workflow/run.py", line 266, in _invoke_step      
    use_cached_job=self.workflow_invocation.use_cached_job)
  File "lib/galaxy/workflow/modules.py", line 1709, in execute
    visit_input_values(tool.inputs, execution_state.inputs, callback, no_replacement_value=NO_REPLACEMENT, replace_optional_connections=True)
...
  File "lib/galaxy/tools/parameters/__init__.py", line 140, in callback_helper
    input_values[input.name] = input.value
AttributeError: 'DataToolParameter' object has no attribute 'value'
```

This only occurs for the assembly and annotation pipeline. Not even for the SISTR pipeline (which also runs Shovill for genome assembly).

## Steps to reproduce the problem
1. Link IRIDA to Galaxy version 20.01
2. Run assembly pipeline.

## Expected behaviour

I expted the pipeline to succeed.

## Additional context
None.

**Comment by apetkau** [comment]
I've tested this out on Galaxy 20.01 again and I cannot reproduce the issue. I suspect that it was related to a specific version of the Galaxy code that has been fixed. I am closing this issue.
