### ISSUE TITLE
staramr (0.4.0) KeyError: 'Predicted Phenotype'

### ISSUE THREAD

**Issue by glwinsor** [phac-nml/irida#686]
## Describe the bug
I've just installed the AMR Detection Pipeline plugin along with staramr 0.4.0 and the rgi repo with RGI 4.2.2 in it. 

All steps leading up to staramr being called seem to work OK but I am getting the following errors:

```
2020-05-08 00:48:39,941 INFO: --output-dir not set. Files will be output to the respective --output-[type] setting
2020-05-08 00:48:39,941 INFO: Will exclude ResFinder/PointFinder genes listed in [/home/ubuntu/miniconda3/envs/__staramr@0.4.0/lib/python3.7/site-packages/staramr/databases/exclude/data/genes_to_exclude.tsv]. Use --no-exclude-genes to disable
2020-05-08 00:48:39,949 INFO: Making BLAST databases for input files
2020-05-08 00:48:40,025 INFO: Scheduling blasts for SRR3028774.fasta
2020-05-08 00:48:42,215 ERROR: 'Predicted Phenotype'
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/__staramr@0.4.0/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 4410, in get_value
    return libindex.get_value_at(s, key)
  File "pandas/_libs/index.pyx", line 44, in pandas._libs.index.get_value_at
  File "pandas/_libs/index.pyx", line 45, in pandas._libs.index.get_value_at
  File "pandas/_libs/util.pxd", line 98, in pandas._libs.util.get_value_at
  File "pandas/_libs/util.pxd", line 83, in pandas._libs.util.validate_indexer
TypeError: 'str' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/__staramr@0.4.0/bin/staramr", line 68, in <module>
    args.run_command(args)
  File "/home/ubuntu/miniconda3/envs/__staramr@0.4.0/lib/python3.7/site-packages/staramr/subcommand/Search.py", line 377, in run
    files=args.files)
  File "/home/ubuntu/miniconda3/envs/__staramr@0.4.0/lib/python3.7/site-packages/staramr/subcommand/Search.py", line 227, in _generate_results
    plength_threshold_pointfinder, report_all_blast)
  File "/home/ubuntu/miniconda3/envs/__staramr@0.4.0/lib/python3.7/site-packages/staramr/detection/AMRDetection.py", line 80, in run_amr_detection
    self._pointfinder_dataframe)
  File "/home/ubuntu/miniconda3/envs/__staramr@0.4.0/lib/python3.7/site-packages/staramr/detection/AMRDetectionResistance.py", line 51, in _create_amr_summary
    return amr_detection_summary.create_summary(self._include_negative_results)
  File "/home/ubuntu/miniconda3/envs/__staramr@0.4.0/lib/python3.7/site-packages/staramr/results/AMRDetectionSummary.py", line 54, in create_summary
    df = self._compile_results(df)
  File "/home/ubuntu/miniconda3/envs/__staramr@0.4.0/lib/python3.7/site-packages/staramr/results/AMRDetectionSummaryResistance.py", line 42, in _compile_results
    .aggregate(self._aggregate_gene_phenotype)
  File "/home/ubuntu/miniconda3/envs/__staramr@0.4.0/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 948, in aggregate
    result = self._aggregate_multiple_funcs([func], _axis=self.axis)
  File "/home/ubuntu/miniconda3/envs/__staramr@0.4.0/lib/python3.7/site-packages/pandas/core/base.py", line 523, in _aggregate_multiple_funcs
    new_res = colg.aggregate(arg)
  File "/home/ubuntu/miniconda3/envs/__staramr@0.4.0/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 253, in aggregate
    ret = self._aggregate_multiple_funcs(func)
  File "/home/ubuntu/miniconda3/envs/__staramr@0.4.0/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 321, in _aggregate_multiple_funcs
    results[name] = obj.aggregate(func)
  File "/home/ubuntu/miniconda3/envs/__staramr@0.4.0/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 269, in aggregate
    result = self._aggregate_named(func, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/__staramr@0.4.0/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 452, in _aggregate_named
    output = func(group, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/__staramr@0.4.0/lib/python3.7/site-packages/staramr/results/AMRDetectionSummaryResistance.py", line 24, in _aggregate_gene_phenotype
    flattened_phenotype_list = [y.strip() for x in dataframe['Predicted Phenotype'].tolist() for y in
  File "/home/ubuntu/miniconda3/envs/__staramr@0.4.0/lib/python3.7/site-packages/pandas/core/series.py", line 871, in __getitem__
    result = self.index.get_value(self, key)
  File "/home/ubuntu/miniconda3/envs/__staramr@0.4.0/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 4418, in get_value
    raise e1
  File "/home/ubuntu/miniconda3/envs/__staramr@0.4.0/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 4404, in get_value
    return self._engine.get_value(s, k, tz=getattr(series.dtype, "tz", None))
  File "pandas/_libs/index.pyx", line 80, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 90, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Predicted Phenotype'
```

My Galaxy Tool parameters are:

```
{
  "use_pointfinder": {
    "__current_case__": "0",
    "enable": "true",
    "organism": "salmonella"
  },
  "genomes1": {
    "id": "eacae5faa35388e8",
    "uuid": "2aaf2adc-aa51-4c34-b268-c10f403e2a41"
  },
  "genomes": {
    "id": "eacae5faa35388e8",
    "uuid": "2aaf2adc-aa51-4c34-b268-c10f403e2a41"
  },
  "__workflow_invocation_uuid__": "da45392690bf11eab50202801bcabc93",
  "dbkey": "?",
  "chromInfo": "/home/ubuntu/galaxy/tool-data/shared/ucsc/chrom/?.len",
  "advanced": {
    "exclude_genes": {
      "__current_case__": "0",
      "exclude_genes_condition": "default"
    },
    "exclude_negatives": "false",
    "exclude_resistance_phenotypes": "false",
    "pid_threshold": "98.0",
    "plength_pointfinder": "95.0",
    "plength_resfinder": "60.0",
    "report_all_blast": "false"
  }
}
```

## Steps to reproduce the problem
What were you doing when you encountered the problem?
1. Add sample to clipboard
2. Click select on AMR Detection pipeline to go to pipeline parameters page
3. Go with default settings and click submit
4. Wait until spades assembly has completed and "Error" state appears

Any ideas how we can overcome this error? Once again, this happens in irida-20.01.2 and galaxy 19.05 running on instance with Ubuntu 18.04.

**Comment by apetkau** [comment]
This looks the same as this issue https://github.com/phac-nml/staramr/issues/115

The solution is to downgrade the version of **pandas** installed in the staramar conda environment. That is activate `__staramr@0.4.0` and run:

```
conda install pandas==0.25.3
```

**Comment by glwinsor** [comment]
Thanks @apetkau that did the trick. Apologies for not seeing that post first.
