### ISSUE TITLE
Users with 'Manager' role cannot manage remote APIs

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#818]
## Describe the bug
If a user with a **Manager** role tries to select the option for **Remote IRIDA Connections** then an `Access Denied` exception occurs and the UI shows nothing.

```
05 Oct. 2020 18:17:02,800 ERROR ca.corefacility.bioinformatics.irida.ria.web.errors.ExceptionHandlerController:81 - Access is
denied
org.springframework.security.access.AccessDeniedException: Access is denied
        at org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:84)
        at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityIntercep
tor.java:233)
        at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityIntercepto
r.java:65)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
        at ca.corefacility.bioinformatics.irida.ria.web.ajax.RemoteAPIAjaxController$$EnhancerBySpringCGLIB$$b6c11142.getAjaxA
PIList(<generated>)
...
```

## Steps to reproduce the problem

1. Setup a remote connection to an IRIDA instance as an Admin.
2. As a user with the Manager role, attempt to select the **Remote IRIDA Connections** menu item.
3. The error will occur.

## Expected behaviour
I expected to be brought to the page to manage remote connections.

## Additional context

**Remote IRIDA connections** menu item:

![image](https://user-images.githubusercontent.com/200517/95141742-9a677800-0737-11eb-871a-7cf915b2f22b.png)

**Comment by joshsadam** [comment]
User / Manage should:

*   \[ \] Needs to see and connect on the listing page.  
*   \[ \] Remove link to details

**Comment by tom114** [comment]
Note this currently will break any users trying to connect remote apis, projects, etc.  This will be fixed as a hotfix.

**Comment by tom114** [comment]
Completed in #821
